version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: loopa-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=loopa_admin
      - MONGO_INITDB_ROOT_PASSWORD=secure_password
      - MONGO_INITDB_DATABASE=loopa_db
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - loopa-network

  mongo-express:
    image: mongo-express
    container_name: loopa-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=loopa_admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secure_password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - loopa-network
    depends_on:
      - mongodb

networks:
  loopa-network:
    driver: bridge

volumes:
  mongodb_data: